BEGIN;

CREATE TABLE PAYMENT
(
    ID                 BIGSERIAL
        PRIMARY KEY,
    ORDER_ID           BIGINT         NOT NULL,
    TOTAL_AMOUNT       NUMERIC(19, 4) NOT NULL,
    STATUS             VARCHAR(255)   NOT NULL,
    PAYMENT_DETAIL     TEXT,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE UNIQUE INDEX PAYMENT_ORDER_ID_UINDEX ON PAYMENT (ORDER_ID);

CREATE TABLE PAYMENT_STATUS_HISTORY
(
    ID                 BIGSERIAL
        PRIMARY KEY,
    PAYMENT_ID         BIGINT       NOT NULL,
    STATUS             VARCHAR(255) NOT NULL,
    PAYMENT_DETAIL     TEXT,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

ALTER TABLE PAYMENT_STATUS_HISTORY
    OWNER TO POSTGRES;

CREATE INDEX PAYMENT_STATUS_HISTORY_PAYMENT_ID_INDEX
    ON PAYMENT_STATUS_HISTORY (PAYMENT_ID);

COMMIT;
